#stage 1
FROM node:latest as node
WORKDIR /app
COPY . .
RUN npm install --legacy-peer-deps
RUN npm run build --prod
#stage 2
FROM nginx:alpine
COPY default.conf /etc/nginx/conf.d/
COPY --from=node /app/dist/sample
 /usr/share/nginx/html
